api_platform:
    mapping:
        paths:
        - '%kernel.project_dir%/config/packages/api_platform/resources/'
    resource_class_directories:
    - '%kernel.project_dir%/src/Entity'
    title: Simple Storefront
    version: 1.0.0
